### ISSUE TITLE
Executive Summary

### ISSUE THREAD

**Issue by ArdaBar** [bounswe/bounswe2019group9#102]
Summary of project status and any changes that are planned for moving forward

- Introduction

- Work done so far

- Road ahead

- Challenges you met as a group

**Comment by irem-uguz** [comment]
Done. The document can be found in the sidebar, under the title Milestone Report 2 as Executive Summary.  [Here](https://github.com/bounswe/bounswe2019group9/wiki/Executive-Summary-2).
