### ISSUE TITLE
Update the requirements according to the feedback

### ISSUE THREAD

**Issue by aliramazanmert** [bounswe/bounswe2019group9#18]

**Comment by ArdaBar** [comment]
According to the feedback mail.

**Comment by corupta** [comment]
done
[bbf9379](https://github.com/bounswe/bounswe2019group9/wiki/Project-Requirements/bbf93795cc4733ea5f0d43ad8e1e2b1ea80381e6)
[9bfc225](https://github.com/bounswe/bounswe2019group9/wiki/Project-Requirements/9bfc2255981cb9cd4a68baa9260f972409a7fdc7)
