### ISSUE TITLE
Handling CORS

### ISSUE THREAD

**Issue by corupta** [bounswe/bounswe2019group9#197]
Hey, since the backend doesn't accept CORS, frontend can't work on different origins. (api.bounswe2019group9.tk and bounswe2019group9.tk and next.bounswe2019group9.tk all count as different origins)

So, either the backend team can enable CORS or a simple reverse proxy set as *bounswe2019group9.tk/api/* => api.bounswe2019group9.tk/$1 can be used.

For now, I've created such reverse proxy on cloudflare, so now, the frontend can function fine (can send & receive messages to backend).

However, I believe that it should be discussed whether allowing CORS would be better.

**Comment by corupta** [comment]
a67cc022a8bfebd80e7033febaad8b083986e785

**Comment by corupta** [comment]
For future reference, below is my cloudflare worker script
```
async function handleRequest(request) {
  let matches = request.url.match(/bounswe2019group9.tk\/api\/(.*)$/);
  if (matches) {
    request = new Request(`https://api.bounswe2019group9.tk/${matches[1]}`, request);
  }
  return fetch(request)
}
addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request))
})
```

**Comment by egemengol** [comment]
Too late for this. Closing.
