### ISSUE TITLE
Create three mock-ups about scenarios

### ISSUE THREAD

**Issue by afgedemenli** [bounswe/bounswe2019group9#27]
- [x] Gamze's web mock-up for Irem's scenario

- [x] Halit's Android mock-up for Ahmet's scenario

- [x] Arda's Android mock-up for Emirhan's scenario

**Comment by corupta** [comment]
[c4192ff](https://github.com/bounswe/bounswe2019group9/commit/c4192fffcee63aaa8c0a5baf5925458da69a260e)
[624554d](
https://github.com/bounswe/bounswe2019group9/commit/624554d489e740a84357468d8ead7274a9432f14)

[a033e94]
(https://github.com/bounswe/bounswe2019group9/wiki/User-Scenarios-and-Mock-ups/a033e94354c163a2d93db3bfb25a404462d1e4c4)
