### ISSUE TITLE
Create profile page

### ISSUE THREAD

**Issue by egemengol** [bounswe/bounswe2019group9#280]
* [x] Create API binding for profile endpoint
* [x] Create profile page
* [x] Create routing

**Comment by egemengol** [comment]
Created API endpoint b0a1ee6895530bccabb163911d2c9cefef41e374

**Comment by egemengol** [comment]
Finished but not pretty 79c28e3b0fd0063b9da1f34ab3f821893c5d92aa

**Comment by corupta** [comment]
https://github.com/bounswe/bounswe2019group9/pull/289
