### ISSUE TITLE
Is this the correct behaviour of user search?

### ISSUE THREAD

**Issue by egemengol** [bounswe/bounswe2019group9#307]
request
```json
{
  "firstName": "john",
  "lastName": "",
  "grade": 5,
  "languageId": ""
}
```
returns response
```json
{
  "status": 200,
  "explanation": null,
  "data": [
    {
      "userId": 12,
      "firstName": "Johnie",
      "lastName": "Walker",
      "email": "j.walker@hotmail.com",
      "languages": [
        "English"
      ],
      "grades": [
        1
      ],
      "progressLevels": [
        0
      ]
    },
    {
      "userId": 30,
      "firstName": "John",
      "lastName": "Johnwell",
      "email": "john@johnwell.com",
      "languages": [
        "English"
      ],
      "grades": [
        5
      ],
      "progressLevels": [
        0
      ]
    }
  ]
}
```
I would guess that Johnnie would not be returned from this query. Is there a rationale, or is this a bug?

**Comment by egemengol** [comment]
In terms of grade

**Comment by afgedemenli** [comment]
Grades are attached to User-Language combinations. A user can't hold a grade without language. There is no such thing as "User's grade". So the system can't know which language you meant when you run a search query with grade. In other words, if you want to filter your search results by grade, you should provide the language id for that grade.

**Comment by afgedemenli** [comment]
Otherwise it will not be filtered. Like the one in your example.
