### ISSUE TITLE
Annotation Implementation on Frontend

### ISSUE THREAD

**Issue by corupta** [bounswe/bounswe2019group9#388]
- [x] Abstract annotation data model handlers
- [x] Add / edit / view annotation on top of essay (Image Body)
- [x] Add / edit / view annotation on top of essay (Text Body)
- [x] Add API connections
- [x] Merge with essay branch when it is available
- [x] Show annotations of owned essays in my essays pages
- [x] Show annotations of essays requested in a separate page.

**Comment by egemengol** [comment]
Done.
