### ISSUE TITLE
Pick and document repos

### ISSUE THREAD

**Issue by aliramazanmert** [bounswe/bounswe2019group9#4]
Pick at least 1 repo and create a documentation page on wiki

**Comment by aliramazanmert** [comment]
Deadline 16.02.2019 23:59

**Comment by irem-uguz** [comment]
I added two repositories under Assignment 1 in wiki page: D3 and Snowplow.

**Comment by emirhanyasin** [comment]
Added a repository by [Adam Geitgey](https://github.com/ageitgey) : [Face Recognition](https://github.com/ageitgey/face_recognition)

**Comment by burhan-akkus-2016400174** [comment]
Added [Stockfish](https://github.com/bounswe/bounswe2019group9/wiki/StockFish) for Assignment 1

**Comment by aliramazanmert** [comment]
Added a repository my own father prepared about a plugin for [SmartClass](https://www.smartclass.com.tr/).

**Comment by afgedemenli** [comment]
Added the repository [amodem](https://github.com/bounswe/bounswe2019group9/wiki/Audio-Modem) for Assignment 1.
