### ISSUE TITLE
Do the welcome page

### ISSUE THREAD

**Issue by corupta** [bounswe/bounswe2019group9#46]

**Comment by egemengol** [comment]
Wrote a draft, comments appreciated

**Comment by ibrahimkaplan07** [comment]
I think the part you wrote is very good. Maybe you can add the group photo and list of the group members (with hyperlink to their personal pages) to the page.

**Comment by egemengol** [comment]
Help from @emirhanyasin is needed for styling the HTML. Images are not positioned properly.
