### ISSUE TITLE
Project Creation -- Consider creating one

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2019group9#48]
You may find it beneficial to create a project from "Projects" tab above. 

It allows you to create boards that make tracking easier and a bit more fun.

**Comment by corupta** [comment]
We've started to experiment with the projects features, we have opened three projects so far,
* [Language Platform](https://github.com/bounswe/bounswe2019group9/projects/1)
   Used for tracking general issues about the project
* [Class Diagram](https://github.com/bounswe/bounswe2019group9/projects/2)
   Used for listing & updating todos to track the progress of the class diagram
* [Sequence Diagram](https://github.com/bounswe/bounswe2019group9/projects/3)
   Used for listing & updating todos to track the progress of the sequence diagrams.
