### ISSUE TITLE
Clear and reshape github project repo folder

### ISSUE THREAD

**Issue by aliramazanmert** [bounswe/bounswe2019group9#49]
/docs folder is too unorganized, both pdfs and images are all in the same folder.These should be grouped in subdirectories.

**Comment by corupta** [comment]
Opening all non project related files to `documentation` branch, removing from master, reorganizing folder hieararchy in the documentation branch, fixing wiki all links in the wiki files.

**Comment by corupta** [comment]
Completed the moving process, please from now on place non-source code material and not deliverables onto documentation branch.

in documentation branch docs folder should contain project/assignment pdfs (documents)
assets folder should contain our assets (eg: images) for our wiki pages and such.
please, keep the assets folder clean as it is.

**Comment by corupta** [comment]
d9149dd
