### ISSUE TITLE
Add contributions to Efforts document

### ISSUE THREAD

**Issue by aliramazanmert** [bounswe/bounswe2019group9#62]
A summary of work done by each team member should be written in efforts document.
- [x] corupta
- [x] afgedemenli
- [x] emirhanyasin
- [x] irem-uguz
- [x] ibrahimkaplan07
- [x] burhan-akkus-2016400174
- [x] ggulbahar
- [ ] egemengol
- [x] aliramazanmert
- [x] ArdaBar

**Comment by irem-uguz** [comment]
This issue is no longer necessary.

**Comment by irem-uguz** [comment]
This issue is no longer needed.
