### ISSUE TITLE
Fill the table about personal efforts in the milestones report

### ISSUE THREAD

**Issue by irem-uguz** [bounswe/bounswe2019group9#67]
Everyone should add their personal efforts to the table in milestones report.
- [x]  Halit
- [x]  Ahmet
- [x]  Emirhan
- [x]  İrem
- [x]  İbrahim
- [x]  Burhan
- [x]  Gamze
- [x]  Egemen
- [x]  Ali
- [x]  Arda

**Comment by emirhanyasin** [comment]
@BurhanAkkus @egemengol @ArdaBar beyler sunu halletsenize kapansin, milestone'a yazdiginizi, personal effort dosyasina kopyala yapistir sadece
