### ISSUE TITLE
Create an account on ProjectLibre 

### ISSUE THREAD

**Issue by ggulbahar** [bounswe/bounswe2019group9#71]
- [ ] Ahmet
- [ ] İrem
- [x] Gamze
- [ ] Egemen
- [ ] İbrahim
- [ ] Arda
- [ ] Ali 
- [ ] Emirhan 
- [ ] Burhan 
- [ ] Halit

**Comment by egemengol** [comment]
There is no need for this anymore. Project Libre is not an online tool. We are trying to find other ways of remote collaborating at the moment.
