### ISSUE TITLE
Open a google document for project plan discussions

### ISSUE THREAD

**Issue by ggulbahar** [bounswe/bounswe2019group9#72]

**Comment by egemengol** [comment]
Opened a [Google Docs document](https://docs.google.com/spreadsheets/d/1Aijbid6Hm0m7EgqCPQHrvIkaiII1wyq9kQkoVC_lToA/edit?usp=sharing), a [Google Sheets document](https://docs.google.com/document/d/1p8WVxaHPHPFmkkK9OakyAB0THoOaQ8UaZxH7gsyUeCg/edit?usp=sharing), and added a [ProjectLibre savefile](https://github.com/bounswe/bounswe2019group9/tree/master/deliverables/Project_Plan) into repository. In which combination are we going to use these tools of collaboration, is not obvious to me. Comments needed.

**Comment by egemengol** [comment]
Will discuss in slack or whatsapp.
