### ISSUE TITLE
Create an Amazon account

### ISSUE THREAD

**Issue by irem-uguz** [bounswe/bounswe2019group9#79]
- [x] Halit 
- [x] Ahmet
- [x] Emirhan
- [ ] İrem
- [x] İbrahim
- [ ] Burhan
- [x] Gamze
- [x] Egemen
- [x] Ali
- [ ] Arda

**Comment by corupta** [comment]
If you haven't, I advise you to first, check out [AWS Educate](https://aws.amazon.com/education/awseducate/) and register via your boun account. Then, create an AWS account linking with the Educate account (I just used the same e-mail)

By doing so, you can occasionally get free AWS credits for having an education account that you can redeem in your AWS account as well as being able to use the benefits of AWS Educate (I'm not an expert on this but you can check it out yourself by googling it)

Note: AWS account and AWS Educate account is different.
